services:
  nmos-crosspoint:
    build:
      context: ./
    image: ghcr.io/qvest-digital/dmf-app-nmos-crosspoint:latest

    container_name: nmos-crosspoint_v3
    hostname: nmos-crosspoint_v3
    domainname: local

    network_mode: host

    volumes:
      - ./server/config:/nmos-crosspoint/server/config
      - ./server/state:/nmos-crosspoint/server/state

    restart: unless-stopped